"""
Writes `atelier-protocol.reg` with the path this repository is actually at.

The checked-in one carries a path, and a path checked into git is wrong for
everybody but the person who wrote it. Run this after moving or cloning the
project and import the result.

Usage:  .venv\\Scripts\\python tools\\write_protocol.py
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
LAUNCHER = HERE / "atelier.cmd"
OUT = HERE / "atelier-protocol.reg"

TEMPLATE = """Windows Registry Editor Version 5.00

; Lets the atelier page ask Windows to start the engine.
;
; A browser cannot launch a program — if one could, every website could. This
; is the one sanctioned way round it: a protocol the page may open, which
; Windows hands to the program named below.
;
; Written under HKEY_CURRENT_USER, so importing it needs no administrator and
; it applies to this account only. Undo it by deleting the same key.
;
; Generated by tools\\write_protocol.py for the copy of the project at:
;     {where}
;
; To install: double-click this file, accept the warning, then restart Chrome.

[HKEY_CURRENT_USER\\Software\\Classes\\atelier]
@="URL:Atelier"
"URL Protocol"=""

[HKEY_CURRENT_USER\\Software\\Classes\\atelier\\shell\\open\\command]
@="\\"{command}\\" \\"%1\\""
"""


def main() -> int:
    if not LAUNCHER.exists():
        print(f"cannot find the launcher at {LAUNCHER}")
        return 1

    # A .reg file wants each backslash in a quoted value doubled.
    command = str(LAUNCHER).replace("\\", "\\\\")
    OUT.write_text(
        TEMPLATE.format(where=LAUNCHER.parent.parent, command=command),
        encoding="utf-8",
        newline="\r\n",
    )
    print(f"wrote {OUT}")
    print(f"   pointing at {LAUNCHER}")
    print("\nDouble-click it to import, then restart the browser.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
