// Copies the version from package.json into a constant the app can import.
//
// The version has to reach the bundle somehow, and the alternatives are worse:
// importing package.json pulls a file from outside src into the compilation,
// and a literal in angular.json is a second place to remember to change. This
// runs before every build (see the prebuild script), so the number on the page
// is whatever package.json says.
import { readFile, writeFile } from 'node:fs/promises';

const { version } = JSON.parse(await readFile('package.json', 'utf8'));
const target = 'src/version.ts';

const contents = `// Generated by scripts/write-version.mjs from package.json. Do not edit.
export const APP_VERSION = '${version}';
`;

const current = await readFile(target, 'utf8').catch(() => '');
if (current !== contents) {
  await writeFile(target, contents, 'utf8');
  console.log(`version: ${target} -> ${version}`);
} else {
  console.log(`version: ${version}`);
}
